AllCops:
  TargetRubyVersion: 3.2
  NewCops: pending
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Layout/IndentationStyle:
  EnforcedStyle: tabs

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false
