#
# © 2026-present https://github.com/<<GitHubUsername>>
#

platform_version=14.3
swift_version=5.9
frameworks=Foundation.framework,AudioToolbox.framework
embedded_frameworks=
flags=-ObjC

# -- Test configuration --------------------------------------------------------
test_platform=iOS Simulator
test_destination_name=iPhone 17
test_os=latest
