#
# © 2026-present https://github.com/ByteBrewIO
#

[versions]
compileSdk = "35"
minSdk = "24"
buildTools = "35.0.0"
android-lib-plugin = "8.6.1"
kotlin-android-plugin = "2.0.21"
undercouch-download-plugin = "5.6.0"
checkstyle = "12.3.1"
openrewrite = "6.27.1"
rewrite-static-analysis = "1.22.0"
node-plugin = "7.1.0"
node-env = "22.0.0"
kotlinx-serialization = "1.6.3"
appcompat = "1.7.1"
play-services-ads-identifier = "18.2.0"
firebase-messaging = "25.0.1"
installreferrer = "2.2"

[libraries]
rewrite-static-analysis = { module = "org.openrewrite.recipe:rewrite-static-analysis", version.ref = "rewrite-static-analysis" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "play-services-ads-identifier" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-lib-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android-plugin" }
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouch-download-plugin" }
openrewrite = { id = "org.openrewrite.rewrite", version.ref = "openrewrite" }
node = { id = "com.github.node-gradle.node", version.ref = "node-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android-plugin" }
