#
# © 2026-present https://github.com/ByteBrewIO
#

gradleProjectName=bytebrew-godot-sdk

# Set plugin-specific extra properties common for all modules
#extra.myProperty=value

# Configure plugin-specific Gradle scripts common for all modules
#gradle.extraGradle=extra.gradle.kts
